name: m1-ios-sideloader
fileGroups:
  - LICENSE
  - README.md
  - project.yml

options:
  deploymentTarget:
    macOS: 12.0
  defaultConfig: Debug
  bundleIdPrefix: com.ericrabil
  createIntermediateGroups: true

packages:
  SwiftCLI:
    url: https://github.com/jakeheis/SwiftCLI
    from: 6.0.3

settings:
  base:
    AD_HOC_CODE_SIGNING_ALLOWED: YES
    FRAMEWORK_SEARCH_PATHS: $(PROJECT_DIR)/Frameworks
    CODE_SIGN_IDENTITY: "-"
    OTHER_SWIFT_FLAGS: "-Xcc -Wno-nullability-completeness -Xcc -Wno-incomplete-umbrella -Xcc -Wno-property-attribute-mismatch -Xcc -Wno-strict-prototypes -Xcc -Wno-arc-performSelector-leaks -Xcc -Wno-objc-protocol-method-implementation -Xcc -Wno-incomplete-umbrella -Xcc -Wno-visibility"
    WARNING_CFLAGS:
      - "-Wno-nullability-completeness"
      - "-Wno-incomplete-umbrella"
      - "-Wno-objc-protocol-method-implementation"
      - "-Wno-arc-performSelector-leaks"
      - "-Wno-strict-prototypes"
      - "-Wno-property-attribute-mismatch"
      - "-Wno-visibility"
    LD_RUNPATH_SEARCH_PATHS:
      - "$(inherited)"
      - "@executable_path/../Frameworks"
      - "@loader_path/Frameworks"
    SWIFT_VERSION: 5.5
    SKIP_INSTALL: YES
    SDKROOT: ""
    ALWAYS_SEARCH_USER_PATHS: NO
    GCC_OPTIMIZATION_LEVEL: 3
    ARCHS:
      - arm64
    VALID_ARCHS: "arm64"
    SUPPORTED_PLATFORMS: "macosx"
    ENABLE_HARDENED_RUNTIME: NO
    SYSTEM_FRAMEWORK_SEARCH_PATHS:
      - "$(inherited)"
      - "$(SDKROOT)$(SYSTEM_LIBRARY_DIR)/PrivateFrameworks"
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
    CODE_SIGNING_ALLOWED: YES
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS:
        - DEBUG

targets:
  # Core
  SideloadKit:
    group: Sources
    templates:
      - BLFramework
    sources:
      - Sources/SideloadKit
    dependencies:
      - target: CSideloadKit
        embed: false
        link: true
  CSideloadKit:
    group: Sources
    templates:
      - BLFramework
    sources:
      - Sources/CSideloadKit
        
  # Tools
  install-ios-app:
    group: Sources
    type: tool
    platform: macOS
    sources:
      - Sources/install-ios-app
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Sources/install-ios-app/ent.plist
        CODE_SIGN_IDENTITY: "-"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/install-ios-app/install-ios-app.h
    dependencies:
      - target: SideloadKit
        embed: true
        link: true
      - target: CSideloadKit
        embed: true
        link: true
      - package: SwiftCLI

targetTemplates:
  BLFramework:
    type: framework
    platform: macOS
    settings:
      base:
        MACH_O_TYPE: staticlib
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DEFINES_MODULE: YES
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
